# Uncomment the next line to define a global platform for your project


target 'Foodie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foodie

pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'

end
